gomaji/urls.py
"""
gomaji url
"""
from django.conf.urls import include, url
from django.contrib import admin
from myshop import views

urlpatterns = [
    url(r'^myshop/', include('myshop.urls', namespace="myshop")),
    url(r'^admin/', include(admin.site.urls)),
]

myshop/urls.py
"""
myshop url
"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<hotel_id>\d+)/vote/$', views.vote, name='vote'),
]

myshop/models.py
import datetime
from django.db import models
from django.utils import timezone

class hotel(models.Model):
    hotel_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.hotel_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()- datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    hotel = models.ForeignKey(hotel)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myshop/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, hotel

def detail(request, hotel_id):
    try:
        hotel = hotel.objects.get(pk=hotel_id)
    except hotel.DoesNotExist:
        raise Http404("hotel does not exist")
    return render(request, 'myshop/detail.html', {'hotel': hotel})

class IndexView(generic.ListView):
    template_name = 'myshop/index.html'
    context_object_name = 'latest_hotel_list'

    def get_queryset(self):
        """Return the last five published hotels."""
        return hotel.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = hotel
    template_name = 'myshop/detail.html'


class ResultsView(generic.DetailView):
    model = hotel
    template_name = 'myshop/results.html'

def results(request, hotel_id):
    hotel = get_object_or_404(hotel, pk=hotel_id)
    return render(request, 'myshop/results.html', {'hotel': hotel})

def vote(request, hotel_id):
    p = get_object_or_404(hotel, pk=hotel_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'myshop/detail.html', {
            'hotel': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('myshop:results', args=(p.id,)))
"""
def index(request):
    return HttpResponse("Hello, world. You're at the myshop index.")

def detail(request, hotel_id):
    return HttpResponse("You're looking at hotel %s." % hotel_id)

def results(request, hotel_id):
    response = "You're looking at the results of hotel %s."
    return HttpResponse(response % hotel_id)

def vote(request, hotel_id):
    return HttpResponse("You're voting on hotel %s." % hotel_id)
"""

templates/myshop/detail.html
<h1>{{ hotel.hotel_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myshop:vote' hotel.id %}" method="post">
{% csrf_token %}
{% for choice in hotel.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

templates/myshop/index.html
{% if latest_hotel_list %}
    <ul>
    {% for hotel in latest_hotel_list %}
       <li><a href="{% url 'myshop:detail' hotel.id %}">{{ hotel.hotel_text }}</a></li>    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/myshop/results.html
<h1>{{ hotel.hotel_text }}</h1>

<ul>
{% for choice in hotel.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'myshop:detail' hotel.id %}">Vote again?</a>